base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('room/<str:room_id>', views.room, name='room'),
    path('create_room/', views.create_room, name='create_room'),
    path('update_room/<str:room_id>', views.update_room, name='update_room'),
    path('delete_room/<str:room_id>', views.delete_room, name='delete_room'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),
    path('delete_message/<str:message_id>', views.delete_message, name='delete_message'),
]

semidis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # Correct import for settings
from django.conf.urls.static import static  # Import the static function
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.


class Room(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey('Topic', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']
        
    def __str__(self):
        return self.name

class Topic(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name    

class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    media = models.FileField(upload_to='media/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body
    

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    avatar = models.ImageField()

    def __str__(self):
        return self.user.email
    

base/forms.py
from django import forms
from django.forms import ModelForm
from .models import Room, Topic, Message
from django.core.exceptions import ValidationError


def validate_file_size(value):
    limit = 10 * 1024 * 1024  # 10 MB in bytes
    if value.size > limit:
        raise ValidationError('File size cannot exceed 10 MB.')

class RoomForm(ModelForm):
    topic = forms.ModelChoiceField(queryset=Topic.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model = Room
        fields = ['topic', 'name', 'description']

class MassageForm(ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)
    media = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control'}), required=False, validators=[validate_file_size])

    def clean_media(self):
        media = self.cleaned_data.get('media')
        if media and not media.content_type.startswith('audio'):
            raise forms.ValidationError('Only audio files are allowed.')
        return media

    class Meta:
        model = Message
        fields = ['body', 'media']

base/views.py
import os
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import Room, Topic, Message
from django.http import HttpResponse
from .forms import RoomForm, MassageForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required



def home(request):
    """
    Handles the home page and search feature.
    """
    # Get the search query from the URL (if any)
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    
    # Get all the rooms (filtered by search query)
    rooms = Room.objects.filter(
                                # Find rooms that match any of the following
                                Q(topic__name__icontains=q) | 
                                Q(name__icontains=q) | 
                                Q(description__icontains=q) | 
                                Q(host__username__icontains=q))
    
    # Get the topic filter from the URL (if any)
    t = request.GET.get('t') if request.GET.get('t') != None else ''
    
    # Filter the rooms by topic name
    rooms = rooms.filter(topic__name__icontains=t)
    
    # Get all the topics
                                
    topics = Topic.objects.all()
    
    # Count the number of rooms
    count = rooms.count()
    
    # Create a context dictionary
    context = {
        'rooms': rooms,  # The filtered rooms
        'topics': topics,  # All the topics
        'count': count   # The number of rooms
    }
    
    # Render the home template with the context
    context = {'rooms': rooms, 'topics': topics}
    return render(request, 'base/home.html', context)


def room(request, room_id):
    room = Room.objects.get(id=room_id)
    messages = room.message_set.all().order_by('-created_at')
    participants = room.participants.all()
    mform = MassageForm()
    if request.method == 'POST':
        mform = MassageForm(request.POST, request.FILES)
        if mform.is_valid():
            massageForm = mform.save(commit=False)
            massageForm.user = request.user
            massageForm.room = room
            massageForm.save()
            room.participants.add(request.user)
            return redirect('room', room_id=room.id)
    context = {'room': room , 'messages': messages , 'participants': participants, 'mform': mform}
    return render(request, 'base/room.html', context)

@login_required(login_url='login')
def create_room(request):
    form = RoomForm()
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            room = form.save(commit=False)  # Create room instance but don't save it yet
            room.host = request.user  # Set the host to the current user
            room.save()  # Now save the room with the host
            return redirect('home')
    context = {'form': form}
    return render(request, 'base/room-form.html', context)

@login_required(login_url='login')
def update_room(request, room_id):
    """
    View to handle the updating of a room
    """
    room = Room.objects.get(id=room_id)
    form = RoomForm(instance=room)
    if request.user != room.host:
        return redirect('home')
    if request.method == 'POST':
        # Get the form data from the request
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            # Save the changes to the database
            form.save()
            # Redirect to the home page
            return redirect('home')
    context = {'form': form}
    return render(request, 'base/room-form.html', context)


@login_required(login_url='login')
def delete_room(request, room_id):
    """
    View to handle the deletion of a room
    
    Args:
        request (HttpRequest): The request object
        room_number (str): The id of the room to delete
    """
    room = Room.objects.get(id=room_id)

    if request.user != room.host:
        return redirect('home')

    if request.method == 'POST':
        # Delete the room when the form is submitted
        room.delete()
        return redirect('home')
    # Render the delete confirmation page
    context = {'room': room}
    return render(request, 'base/delete.html', context)


@login_required(login_url='login')
def delete_message(request, message_id):
    message = Message.objects.get(id=message_id)
    if request.user != message.user:
        return redirect('home')
    message.delete()
    return redirect('room', room_id=message.room.id)

@receiver(post_delete, sender=Message)
def delete_media_message(sender, instance, **kwargs):
    if instance.media:
        if os.path.isfile(instance.media.path):
            os.remove(instance.media.path)

def loginPage(request):
    page = 'login'
    # If the user is already authenticated, redirect to the home page
    
    if request.user.is_authenticated:
        return redirect('home')
    
    # Handling the POST request to authenticate the user
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                # Optional: You can add an error message here for invalid login
                pass
        else:
            # Optional: Handle form errors here
            pass
    else:
        form = AuthenticationForm()

    context = {'form': form, 'page': page}
    return render(request, 'base/login_register.html', context)


def registerPage(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    page = 'register'
    context = {'form': form, 'page': page}
    return render(request, 'base/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('home')

base/templates/base/delete.html
{% extends "main.html" %}

{% block content %}

<h1>Room of : {{ room.name }} </h1>
<div>
    <form action="" method="post">
        {% csrf_token %}
        <h3> are you sure you want to delete?</h3>
        <a class="btn btn-primary" href="{% url 'home' %}">Cancel</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
</div>
{% endblock %}

base/templates/base/home.html
{% extends "main.html" %}

{% block content %}

<style>
    .home-content{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
        grid-gap: 20px;
    }
</style>

<h1>Home Template</h1>
<hr>
<div class= "home-content">
    
    <div class="home-topics" style="text-align: center; padding: 10px;">

        <h3>Topics</h3>
        <hr>
        <div style='padding: 10px;'>
            <a class="btn btn-light btn-lg" href="{% url 'home' %}">All</a>
        </div>
        {% for topic in topics %}
            <div style='padding: 10px;'>
                <a class="btn btn-light btn-lg" href="{% url 'home' %}?t={{topic.name|urlencode}}">{{topic.name}}</a>
            </div>
        {% endfor %}

    </div>

    
    <div>
        <h3>Rooms available : {{ rooms.count }}</h3>
        <a class="btn btn-success" href="{% url 'create_room' %}">Create Room</a>
        <hr>
        <div>
            <div class="row row-cols-md-6 mb-1 text-center">
                <div class="col themed-grid-col"><h5>Host</h5></div>
                <div class="col themed-grid-col"><h5>Name</h5></div>
                <div class="col themed-grid-col"><h5>Topic</h5></div>
                <div class="col themed-grid-col"><h5></h5></div>
                <div class="col themed-grid-col"><h5>Created From</h5></div>
                <div class="col themed-grid-col"><h5>Last Updated</h5></div>
            </div>
            <hr>
            {% for room in rooms %}
                <div class="row row-cols-md-6 mb-1 text-center">
                    <div class="col themed-grid-col">
                        <h6>@{{room.host}}</h6>
                    </div>
                    <div class="col themed-grid-col">
                        <a class="h5"  href="{% url 'room' room_id=room.id %}">{{ room.name }}</a>
                    </div>
                    <div class="col themed-grid-col">
                        <p class="lead">{{room.topic}}</p>
                    </div>
                    <div class="col themed-grid-col">
                        {% if request.user == room.host %}
                            <div class="row">
                            <a class="btn btn-warning" href="{% url 'update_room' room_id=room.id %}">Update Room</a>
                            </div>
                            <div class="row">
                            <a class="btn btn-danger" href="{% url 'delete_room' room_id=room.id %}">Delete Room</a>
                            </div>
                        {% else %}
                            <a></a>
                            <a></a>
                        {% endif %}
                    </div>
                    <div class="col themed-grid-col">
                        <small>{{room.created_at|timesince}}</small>
                    </div>
                    <div class="col themed-grid-col">
                        <small>{{room.updated_at|timesince}}</small>
                    </div>
                </div>
                <hr>
            {% endfor %} 
        </div>
    </div>
</div>



{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %}

{% block content %}


<body class="text-center"></body>
<div>
    <h1>Login/Register</h1>
    <hr>
    <div class="container mt-6">
        <form action="" method="POST" class="form-signin">
            {% csrf_token %}
            {{ form }}
            {% if page == 'login' %}
            <input class="btn btn-primary" style="margin-top: 10px;" type="submit" value="Login">
            {% else %}
            <input class="btn btn-primary" style="margin-top: 10px;" type="submit" value="Register">
            {% endif %}
        </form>
    </div>

</div>
</body>



{% endblock %}

base/templates/base/room-form.html
{% extends "main.html" %}

{% block content %}
<div>
    <h1>Create Room Form</h1>
    <hr>
</div>

<div class="container mt-5">
    <div class="form">
        <form action="" method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>

{% endblock %}

base/templates/base/room.html
{% extends "main.html" %}

{% block content %}

<style>
    .room-content{
        display: grid;
        grid-template-columns: 3fr 1fr;
        grid-gap: 20px;
    }
</style>

<h1>Room name : {{ room.name }} </h1>
<h3>About : <a class="btn btn-light btn-lg" href="{% url 'home' %}?t={{room.topic|urlencode}}">{{room.topic}}</a></h3>
<h5>Created by : @{{ room.host }}</h5>
<hr>
<div class="h5">
    <p>{{ room.description }}</p>
</div>
<div class="room-content">
    <div>
        <h3>Messages</h3>
        <hr>
        <div class="container">
            <div class="list-group">
            {% for message in messages %}
                <div class="list-group-item list-group-item-action d-flex gap-3 py-3">
                    <p>@{{message.user}}: {{message.body}} </p>
                        {% with extensions=".jpg,.png,.jpeg" %}
                        {% if message.media.url|slice:"-4:" in extensions %}
                        <img src="{{message.media.url}}" alt="message" width="50px" height="50px">
                        {% endif %}
                        {% endwith %}
                        {% with extensions=".mp4,.mkv,.webm" %}
                        {% if message.media.url|slice:"-4:" in extensions %}
                        <video width="320" height="240" controls>
                            <source src="{{message.media.url}}" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                        {% endif %}
                        {% endwith %}
                        {% with extensions=".mp3,.wav,.ogg" %}
                        {% if message.media.url|slice:"-4:" in extensions %}
                        <audio controls>
                            <source src="{{message.media.url}}" type="audio/mpeg">
                            Your browser does not support the video tag.
                        </audio>
                        {% endif %}
                        {% endwith %}

                    {% if request.user == message.user %}
                    <a class="btn btn-danger" href="{% url 'delete_message' message_id=message.id %}">Delete</a>
                    {% endif %}
                    {% if message.media %}
                    <a class="btn btn-primary" href="{{message.media.url}}">Download</a>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
            {% if request.user.is_authenticated %}
            <hr>
            <form action="" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <div class="form">
                    {{ mform.as_p }}
                    <input type="file" id="id_media" name="media" accept="audio/*" style="display: none;">
                    <div>
                        <button type="button" id="record-btn" class="btn btn-secondary">Record Voice</button>
                        <button type="button" id="stop-btn" class="btn btn-danger" style="display: none;">Stop Recording</button>
                        <audio id="audio-preview" controls style="display:none;"></audio>
                    </div>
                </div>
                <button class="btn btn-primary" style="margin-top: 10px; margin-bottom: 10px;" type="submit">Send</button>
            </form>
            {% endif %}
        </div>
    </div>

    <div>
        <h3>Participants</h3>
        <hr>
        <div class="container">
            <div class="list-group">
            {% for user in participants %}
                <div class="list-group-item list-group-item-action d-flex gap-3 py-3">
                    <p>@{{user.username}}</p>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>

<script>
    let recordBtn = document.getElementById('record-btn');
    let stopBtn = document.getElementById('stop-btn');
    let audioPreview = document.getElementById('audio-preview');
    let mediaInput = document.getElementById('id_media');

    let chunks = [];
    let mediaRecorder;
    let audioBlob;

    recordBtn.addEventListener('click', async () => {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
        mediaRecorder = new MediaRecorder(stream);
        mediaRecorder.start();

        recordBtn.style.display = 'none';
        stopBtn.style.display = 'inline-block';

        mediaRecorder.ondataavailable = function(e) {
            chunks.push(e.data);
        };

        mediaRecorder.onstop = function() {
            audioBlob = new Blob(chunks, { 'type': 'audio/ogg; codecs=opus' });
            chunks = [];

            const audioURL = URL.createObjectURL(audioBlob);
            audioPreview.src = audioURL;
            audioPreview.style.display = 'block';

            // Create a File object from the Blob and set it as the input file for form submission
            const file = new File([audioBlob], 'recording.ogg', { type: 'audio/ogg' });
            const dataTransfer = new DataTransfer();
            dataTransfer.items.add(file);
            mediaInput.files = dataTransfer.files; // Update the hidden file input with the recorded audio
            mediaInput.style.display = 'none';
        };
    });

    stopBtn.addEventListener('click', () => {
        mediaRecorder.stop();
        recordBtn.style.display = 'inline-block';
        stopBtn.style.display = 'none';
    });
</script>

{% endblock %}